services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${ENV:-dev}
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/shazamdb.sqlite:/app/shazamdb.sqlite
    environment:
      ENV: ${ENV}

  client:
    build:
      context: ./svelte-kit
      dockerfile: Dockerfile
      target: ${ENV:-dev}
    ports:
      - "5173:5173"
    volumes:
      - ./svelte-kit/src:/app/src
      - ./svelte-kit/vite.config.ts:/app/vite.config.ts
      - ./svelte-kit/svelte.config.js:/app/svelte.config.js
      - ./svelte-kit/.svelte-kit:/app/.svelte-kit
      - ./svelte-kit/static:/app/static
    environment:
      ENV: ${ENV}
      SERVER_API: http://server:3000
